# Generated by Django 5.2.7 on 2025-10-04 13:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cnae', models.CharField(max_length=10)),
                ('cnae_descricao', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='Cascavel', max_length=100)),
                ('uf', models.CharField(default='PR', max_length=2)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('porte', models.CharField(choices=[('MEI', 'Microempreendedor Individual'), ('ME', 'Microempresa'), ('EPP', 'Empresa de Pequeno Porte'), ('MEDIA', 'Empresa de Médio Porte'), ('GRANDE', 'Empresa de Grande Porte')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CONSULTA', 'Consulta'), ('UPLOAD', 'Upload de Dados'), ('CALCULO', 'Cálculo Realizado'), ('EXPORTACAO', 'Exportação de Relatório'), ('ALTERACAO', 'Alteração de Dados'), ('EXCLUSAO', 'Exclusão de Dados')], max_length=20)),
                ('tabela', models.CharField(blank=True, max_length=50)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('detalhes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('BC_BAIXO', 'Relação B/C Abaixo de 1'), ('SEM_RECOLHIMENTO', 'Sem Recolhimento'), ('CONTRAPARTIDA_VENCENDO', 'Contrapartida Vencendo'), ('IMPACTO_NEGATIVO', 'Impacto Líquido Negativo'), ('INCENTIVO_VENCENDO', 'Incentivo Vencendo')], max_length=30)),
                ('descricao', models.TextField()),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('data_alerta', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('RESOLVIDO', 'Resolvido'), ('IGNORADO', 'Ignorado')], default='ATIVO', max_length=10)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resolvidos', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(db_column='cnpj', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.empresa', to_field='cnpj')),
            ],
            options={
                'db_table': 'alertas',
                'ordering': ['-data_alerta', '-severidade'],
            },
        ),
        migrations.CreateModel(
            name='Incentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento_legal', models.CharField(max_length=100)),
                ('tipo_incentivo', models.CharField(choices=[('ISENCAO_ISS', 'Isenção de ISS'), ('REDUCAO_ISS', 'Redução de ISS'), ('ISENCAO_IPTU', 'Isenção de IPTU'), ('REDUCAO_IPTU', 'Redução de IPTU'), ('ISENCAO_TAXAS', 'Isenção de Taxas'), ('TERRENO_GRATUITO', 'Terreno Gratuito'), ('MISTO', 'Incentivo Misto')], max_length=20)),
                ('percentual_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valor_fixo_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('contrapartidas', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('baseline_iss_12m', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('baseline_iptu_12m', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_column='cnpj', on_delete=django.db.models.deletion.CASCADE, related_name='incentivos', to='api.empresa', to_field='cnpj')),
            ],
            options={
                'db_table': 'incentivos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Contrapartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('EMPREGOS', 'Geração de Empregos'), ('INVESTIMENTO', 'Investimento em Infraestrutura'), ('QUALIFICACAO', 'Qualificação Profissional'), ('PERMANENCIA', 'Permanência no Município'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('CUMPRIDA', 'Cumprida'), ('DESCUMPRIDA', 'Descumprida')], default='PENDENTE', max_length=20)),
                ('data_cumprimento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incentivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrapartidas_detalhadas', to='api.incentivo')),
            ],
            options={
                'db_table': 'contrapartidas',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='CalculoImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('custo_fiscal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('arrecadacao_incremental', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impacto_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bc_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('payback_meses', models.IntegerField(blank=True, null=True)),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_column='cnpj', on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='api.empresa', to_field='cnpj')),
            ],
            options={
                'db_table': 'calculos_impacto',
                'ordering': ['-calculado_em'],
                'unique_together': {('empresa', 'periodo_inicio', 'periodo_fim')},
            },
        ),
        migrations.CreateModel(
            name='ArrecadacaoISS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ref', models.DateField()),
                ('valor_iss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_base_calculo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('numero_nfse', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(db_column='cnpj', on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacao_iss', to='api.empresa', to_field='cnpj')),
            ],
            options={
                'db_table': 'arrecadacao_iss',
                'ordering': ['-mes_ref'],
                'unique_together': {('empresa', 'mes_ref')},
            },
        ),
        migrations.CreateModel(
            name='ArrecadacaoIPTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_ref', models.IntegerField()),
                ('valor_iptu', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_taxas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_alvara', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(db_column='cnpj', on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacao_iptu', to='api.empresa', to_field='cnpj')),
            ],
            options={
                'db_table': 'arrecadacao_iptu_taxas',
                'ordering': ['-ano_ref'],
                'unique_together': {('empresa', 'ano_ref')},
            },
        ),
    ]
